language: node_js
cache:
  npm: true
  directories:
    - node_modules
    - '~/.cache'
node_js:
  - '10'
env:
  - CXX=g++-4.8]
addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgconf-2-4
before_script:
  - echo "Create Database"
  - psql -c 'create database testroundhouse;' -U postgres
script:
  - npm run test:mocha
services:
  - postgresql
deploy:
  provider: heroku
  api_key:
    secure: FxmTlv6qR3ZcbRoOZuxT3/0AYUQ8Bhzj1LY+P80v3oMcZ06Q4CYEqd1FqfzQHz1pguhwjqP68Ph777AWYsB6f9TZrU/0bsepqi36sAtTbq9fP8tltWvfbjNsCj1ayF5yAQXSQ52srwUP7p32lGIPfRZGVloQKyvCcCJ9m6go1jULxOsCwUbPttHgJvu7HWwaX5lgkKvaoIKUAQ8bcQWIXVhhLsZpHHZ703UVKhNUCG0sT2N6dtG7Roank9QHJC2jLZrmsWx/1Ab0t1Y7hZra59VrZ9JLhaMfvcsnDpQZSe+RiR1pmlPpHionDkmodAHOQXJKVVGtVmtC/wq6IUMc4bUhnUdktJgOXZoOcYg1jOHafKfr5e1pGGla5K9iaoh4guwpnk7PlDP/fJNR56Yz23fBfUXNaT0g6vcH3dAhaIVROcOglG/6Q0HMGr5G+wPGD7fBLdIoBoyZ+DNDe15ej6uuYk51Gc5qWf9VeD3VcS1DIhyZO5K7R4OyUEKDpowLSsL2aQhOl70o9rYIpli+raM2fJoBTaPANfASrahb5UaS7KU6BR1NqmoT4U/jw9JgoV7Gn67b0ydblvn/Em7h0RgvpyMbOeZ+3SmCdm4yuOqAVn/93z3EbU92Ivl7e0VtCbGTI4TsEnwRETEt5CrOapR1SIIydgN9h8JQiqC50Kc=
  app: roundhouseapp
