before_script:
  - psql -c 'create database testRoundhouse;' -U postgres
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "10"
env:
  - CXX=g++-4.8
  - POSTGRES_HOST=localhost
  - POSTGRES_PORT=5433
  - POSTGRES_DB=testRoundhouse
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=
  - SECRET_KEY=asdfasd7897asdfa6h2nkajkhaeynakuinayyuieyaaehwwunas
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run test:mocha
services:
  - postgresql
deploy:
  provider: heroku
  api_key:
    secure: "cf0e05d9-4eca-4948-a012-b91fe9704bab"