language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "10"
env:
  - CXX=g++-4.8]
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - echo "Create Database"
  - psql -c 'create database testroundhouse;' -U postgres
script:
  - npm run test:mocha
  - npm run start:test && cypress:run --record
services:
  - postgresql
deploy:
  provider: heroku
  api_key:
    secure: "17c9077e-3526-4306-aefa-928c3ad8ed48"
  app: "roundhouseapp"