language: node_js
cache:
  npm: true
  directories:
    - node_modules
    - '~/.cache'
node_js:
  - '10'
env:
  - CXX=g++-4.8]
addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgconf-2-4
before_script:
  - echo "Create Database"
  - psql -c 'create database testroundhouse;' -U postgres
script:
  - npm run test:mocha
services:
  - postgresql
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: roundhouseapp
