language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run test:mocha
deploy:
  provider: heroku
  api_key:
    secure: "cf0e05d9-4eca-4948-a012-b91fe9704bab"